date: "{{ ('%Y' | strftime)}}" # date actuelle
date_full: "{{ ( '%Y-%m-%d %H_%M_%S' | strftime ) }}" # date actuelle complÃ©te, pour faire des tests
database: "getent_shadow.{{ user_name }}"
home_path: "{{ user_type | get_home_path(user_name,user_year) }}"